services:
  mysqldb_crm:
    image: mysql:8.4
    container_name: mysql_crm
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: public
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    ports:
      - "3301:3306"

volumes:
  mysql_data:
    name: crm_data_mysql