"""c0 - Inicio do banco de dados superbase

Revision ID: f6dd56fc71da
Revises: 66308bcb3954
Create Date: 2026-03-28 13:48:37.246264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6dd56fc71da'
down_revision: Union[str, Sequence[str], None] = '66308bcb3954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
